sitewomen/sitewomen/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from sitewomen import settings
from women.views_01 import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('women.urls')),
    path('users/', include('users.urls', namespace='users')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

sitewomen/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordChangeView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = 'users'

urlpatterns = [
    # path('login/', views.login_user, name='login'),
    path('login/', views.LoginUser.as_view(), name='login'),

    # path('logout/', LogoutView.as_view(), name='logout'), # не работает
    path('logout/', views.logout_user, name='logout'),

    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),

    path('password-change/', views.UserPasswordChange.as_view(), name="password_change"),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name="password_change_done"),

    path('password-change/', views.UserPasswordChange.as_view(), name="password_change"),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name="password_change_done"),

    path('password-reset/',
         PasswordResetView.as_view(
             template_name="users/password_reset_form.html",
             email_template_name="users/password_reset_email.html",
             success_url=reverse_lazy("users:password_reset_done")
         ),
         name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name="users/password_reset_confirm.html",
             success_url=reverse_lazy("users:password_reset_complete")
         ),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),

]

sitewomen/templates/base_actual.html
{% load static %}
{% load women_tags %}

<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'women/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'women/images/main.ico' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>
{% block mainmenu %}
		<div class="header">
			<ul id="mainmenu" class="mainmenu">
			<li class="logo"><a href="{% url 'home' %}"><div class="logo"></div></a></li>
{% for m in mainmenu %}
	<li><a href="{% url m.url_name %}">{{m.title}}</a></li>
{% endfor %}
{% if user.is_authenticated %}
    <li class="last"> <a href="{% url 'users:profile' %}">{{ user.username }}</a> | <a href="{% url 'users:logout' %}">Выйти</a></li>
{% else %}
    <li class="last"><a href="{% url 'users:login' %}">Войти</a> | <a href="{% url 'users:register' %}">Регистрация</a></li>
{% endif %}
			</ul>
			<div class="clear"></div>
		</div>
{% endblock mainmenu %}


<table class="table-content" border=0 cellpadding="0" cellspacing="0">
<tr>
<!-- Sidebar слева -->
	<td valign="top" class="left-chapters">
	<ul id="leftchapters">
		{% if cat_selected == 0 %}
		<li class="selected">Все категории</li>
		{% else %}
		<li><a href="{% url 'home' %}">Все категории</a></li>
		{% endif %}

		{% show_categories cat_selected %}

		<li class="share">
		<p>Наш канал</p>
		<a class="share-yt" href="https://www.youtube.com/channel/UClJzWfGWuGJL2t-3dYKcHTA/playlists" target="_blank" rel="nofollow"></a>
		</li>

		<li>{% show_all_tags %}</li>
	</ul>
</td>
<!-- Конец Sidebar'а -->
<td valign="top" class="content">
	<!-- Хлебные крошки -->
	{% block breadcrumbs %}
	{% endblock %}

<!-- Блок контента -->
	<div class="content-text">
{% block content %}
{% endblock %}
	</div>
<!-- Конец блока контента -->

{% block navigation %}
{% endblock %}

</td></tr></table>
</td></tr>
<!-- Footer -->
<tr><td valign=top>
	<div id="footer">
		<p>&copy; 2023 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах, в том числе и бумажных, строго запрещено.</p>
	</div>
</td></tr></table>
<!-- Конец footer'а и страницы -->
</body>
</html>

sitewomen/templates/base_old_1.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link type="text/css" href="{% static 'women/css/styles.css' %}" rel="stylesheet" />
</head>
<body>

<!--главное меню-->
<ul>
    <li><a href="{% url 'home' %}">Главная страница</a></li>
    {% for x in menu %}
        {% if not forloop.last %}
            <li>
        {% else %}
            <li class="last">
        {% endif %}
            <a href="{% url x.url_name %}">{{ x.title }}</a>
        </li>
    {% endfor %}
</ul>

{% block content %} {% endblock %}

</body>
</html>

sitewomen/templates/base_old_2.html
{% load static %}
{% load women_tags %}

<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'women/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'women/images/main.ico' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>
{% block mainmenu %}
		<div class="header">
			<ul id="mainmenu" class="mainmenu">
			<li class="logo"><a href="{% url 'home' %}"><div class="logo"></div></a></li>
{% for m in menu %}
	{% if not forloop.last %}<li>{% else %}<li class="last">{% endif %}
		<a href="{% url m.url_name %}">{{m.title}}</a></li>
{% endfor %}
			</ul>
			<div class="clear"></div>
		</div>
{% endblock mainmenu %}


<table class="table-content" border=0 cellpadding="0" cellspacing="0">
<tr>
<!-- Sidebar слева -->
	<td valign="top" class="left-chapters">
	<ul id="leftchapters">

{#        # вывод категорий через свой шаблонный тег#}
        {% get_cat as categories %}
        <li class="selected">Все категории</li>
        {% for cat in categories %}
            <li><a href="{% url 'category' cat.id %}">{{ cat.name }}</a></li>
        {% endfor %}


{#        # простой вывод#}
{#		<li class="selected">Все категории</li>#}
{#		<li><a href="#">Актрисы</a></li>#}
{#		<li><a href="#">Певицы</a></li>#}
{#		<li><a href="#">Спортсменки</a></li>#}
		<li class="share">
		<p>Наш канал</p>
		<a class="share-yt" href="https://www.youtube.com/channel/UClJzWfGWuGJL2t-3dYKcHTA/playlists" target="_blank" rel="nofollow"></a>
		</li>
	</ul>
</td>
<!-- Конец Sidebar'а -->
<td valign="top" class="content">
	<!-- Хлебные крошки -->
	{% block breadcrumbs %}
	{% endblock %}

<!-- Блок контента -->
	<div class="content-text">
{% block content %}
{% endblock %}
	</div>
<!-- Конец блока контента -->

</td></tr></table>
</td></tr>
<!-- Footer -->
<tr><td valign=top>
	<div id="footer">
		<p>&copy; 2023 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах, в том числе и бумажных, строго запрещено.</p>
	</div>
</td></tr></table>
<!-- Конец footer'а и страницы -->
</body>
</html>

sitewomen/templates/base_old_3.html
{% load static %}
{% load women_tags %}

<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'women/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'women/images/main.ico' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>
{% block mainmenu %}
		<div class="header">
			<ul id="mainmenu" class="mainmenu">
			<li class="logo"><a href="{% url 'home' %}"><div class="logo"></div></a></li>
{% for m in mainmenu %}
	{% if not forloop.last %}<li>{% else %}<li class="last">{% endif %}
		<a href="{% url m.url_name %}">{{m.title}}</a></li>
{% endfor %}
			</ul>
			<div class="clear"></div>
		</div>
{% endblock mainmenu %}


<table class="table-content" border=0 cellpadding="0" cellspacing="0">
<tr>
<!-- Sidebar слева -->
	<td valign="top" class="left-chapters">
	<ul id="leftchapters">
		{% if cat_selected == 0 %}
		<li class="selected">Все категории</li>
		{% else %}
		<li><a href="{% url 'home' %}">Все категории</a></li>
		{% endif %}

		{% show_categories cat_selected %}

		<li class="share">
		<p>Наш канал</p>
		<a class="share-yt" href="https://www.youtube.com/channel/UClJzWfGWuGJL2t-3dYKcHTA/playlists" target="_blank" rel="nofollow"></a>
		</li>

        <li>{% show_all_tags %}</li>

	</ul>
</td>
<!-- Конец Sidebar'а -->
<td valign="top" class="content">
	<!-- Хлебные крошки -->
	{% block breadcrumbs %}
	{% endblock %}

<!-- Блок контента -->
	<div class="content-text">
{% block content %}
{% endblock %}
	</div>
<!-- Конец блока контента -->

{% block navigation %}
{% endblock %}

</td></tr></table>
</td></tr>
<!-- Footer -->
<tr><td valign=top>
	<div id="footer">
		<p>&copy; 2023 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах, в том числе и бумажных, строго запрещено.</p>
	</div>
</td></tr></table>
<!-- Конец footer'а и страницы -->
</body>
</html>